version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: ["dagster", "dev"]
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: