name: 'medical_data_warehouse'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medical_data_warehouse:
    marts:
      +materialized: table
      +schema: marts
    staging:
      +materialized: view
      +schema: staging